name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Nightly Toolchain
      run: rustup toolchain install nightly
    - uses: actions/checkout@v4
    - name: Unit Test Worspace
      run: cargo test --workspace
    - name: Unit Test Features
      run: cargo test --features redundant_generics
    - name: Bench Check
      run: cargo +nightly bench --no-run
    - name: Code Formatting
      run: cargo fmt --check
