name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Nightly Toolchain
      run: rustup toolchain install nightly
    - uses: actions/checkout@v4
    - name: Test
      run: cargo +nightly test
